PORTAFOLIO_URL="https://portafolio-red-sun.reflex.run/"
LINKEDIN_URL="https://www.linkedin.com/in/juan-david-ballesteros-413350260"
GITHUB_URL="https://github.com/jballesteros28?tab=repositories"
INSTAGRAM_URL="https://www.instagram.com/j_ballesteros28"
FACEBOOK_URL="https://www.facebook.com/juandavid.ballesterosbayona"
TWITTER_URL="https://x.com/juandavidb59924"
EMAIL_URL=""
CV_URL="https://docs.google.com/document/d/1WOpbNoJyD_OqHPGzCyS6mfqmsk8dLjUl/edit"